"""Narrow provider boundaries used by the BoomEarth V1 workbench."""

from .tikhub import (
    AccountStatus,
    AuthorizationRequiredError,
    InvalidTikHubBaseError,
    SourceMedia,
    TikHubClient,
    TikHubCredentialError,
    TikHubError,
    TikHubForbiddenError,
    TikHubHTTPError,
    TikHubMalformedPayloadError,
    TikHubNonSuccessPayloadError,
    TikHubPaymentRequiredError,
    TikHubPayloadError,
    TikHubRateLimitError,
    TikHubResponseError,
    TikHubServerError,
    TikHubTransportError,
    TikHubUnauthorizedError,
    UnsupportedSourceURLError,
)
from .ytdlp import YtDlpError, YtDlpProvider, YtDlpResult
from .tikhub_download import (
    MAX_MEDIA_BYTES,
    PrivateMediaDownloader,
    TikHubDownloadError,
)
from .tikhub_bilibili import (
    TikHubBilibiliClient,
    TikHubBilibiliCredentialError,
    TikHubBilibiliError,
    TikHubBilibiliHTTPError,
    TikHubBilibiliPayloadError,
    TikHubBilibiliResponse,
    TikHubBilibiliResponseError,
    TikHubBilibiliTimeoutError,
    TikHubBilibiliTransportError,
)
from .bilibili_media_download import (
    MAX_MEDIA_BYTES as BILIBILI_MAX_MEDIA_BYTES,
    BilibiliMediaDownloadError,
    BilibiliMediaDownloader,
    DownloadedBilibiliAsset,
)

__all__ = [
    "AccountStatus",
    "AuthorizationRequiredError",
    "BILIBILI_MAX_MEDIA_BYTES",
    "BilibiliMediaDownloadError",
    "BilibiliMediaDownloader",
    "DownloadedBilibiliAsset",
    "InvalidTikHubBaseError",
    "MAX_MEDIA_BYTES",
    "PrivateMediaDownloader",
    "SourceMedia",
    "TikHubClient",
    "TikHubCredentialError",
    "TikHubDownloadError",
    "TikHubError",
    "TikHubBilibiliClient",
    "TikHubBilibiliCredentialError",
    "TikHubBilibiliError",
    "TikHubBilibiliHTTPError",
    "TikHubBilibiliPayloadError",
    "TikHubBilibiliResponse",
    "TikHubBilibiliResponseError",
    "TikHubBilibiliTimeoutError",
    "TikHubBilibiliTransportError",
    "TikHubForbiddenError",
    "TikHubHTTPError",
    "TikHubMalformedPayloadError",
    "TikHubNonSuccessPayloadError",
    "TikHubPaymentRequiredError",
    "TikHubPayloadError",
    "TikHubRateLimitError",
    "TikHubResponseError",
    "TikHubServerError",
    "TikHubTransportError",
    "TikHubUnauthorizedError",
    "UnsupportedSourceURLError",
    "YtDlpError",
    "YtDlpProvider",
    "YtDlpResult",
]
